#!/bin/bash

# Initialize METAL with default settings
metal
#THIS SCRIPT EXECUTES AN ANALYSIS OF EIGHT STUDIES
#THE RESULTS FOR EACH STUDY ARE STORED IN FILES Inputfile1.txt THROUGH Inputfile8.txt

#LOAD THE FIRST EIGHT INPUT FILES

# UNCOMMENT THE NEXT LINE TO ENABLE GenomicControl CORRECTION
# GENOMICCONTROL ON

SCHEME STDERR
AVERAGEFREQ ON
MINMAXFREQ ON
# === DESCRIBE AND PROCESS THE FIRST INPUT FILE ===
MARKER ID
ALLELE REF ALT
EFFECT log(OR)
FREQLABEL A1_FREQ
PVALUE P
STDERR LOG(OR)_SE
WEIGHT OBS_CT

PROCESS P12_plink2_200324_rs2853677.STATUS_CASE.glm.logistic.hybrid 
PROCESS P3_plink2_200324_rs2853677.STATUS_CASE.glm.logistic.hybrid 
PROCESS PC4_plink2_200324_rs2853677.PHENO1.glm.logistic.hybrid


# === THE SECOND INPUT FILE HAS THE SAME FORMAT AND CAN BE PROCESSED IMMEDIATELY ===

#for the final meta-analysis of all 8 samples only output results if the
#combined weight is greater than 10000 people

OUTFILE Plink2_freq_METAANALYSIS.tbl
ANALYZE

QUIT
